-- =====================================================================
-- PlantPulse | 00 - Foundation: warehouse, database, schemas, tables
-- IT (ERP/CMMS) and OT (sensor telemetry) land side by side in Snowflake
-- =====================================================================
USE ROLE ACCOUNTADMIN;   -- or any role with CREATE DATABASE / WAREHOUSE

CREATE WAREHOUSE IF NOT EXISTS PLANTPULSE_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'PlantPulse predictive maintenance & OEE command center';

CREATE DATABASE IF NOT EXISTS PLANTPULSE COMMENT = 'PlantPulse - IT/OT converged maintenance data';
CREATE SCHEMA IF NOT EXISTS PLANTPULSE.OT        COMMENT = 'Operational technology: machine telemetry';
CREATE SCHEMA IF NOT EXISTS PLANTPULSE.ERP       COMMENT = 'Enterprise systems: asset master, CMMS work orders, inventory, production';
CREATE SCHEMA IF NOT EXISTS PLANTPULSE.KNOWLEDGE COMMENT = 'Unstructured maintenance knowledge: manuals, SOPs';
CREATE SCHEMA IF NOT EXISTS PLANTPULSE.ANALYTICS COMMENT = 'Features, ML, search, semantic layer, automation';

USE WAREHOUSE PLANTPULSE_WH;
USE DATABASE PLANTPULSE;

-- ---------- OT ----------
CREATE OR REPLACE TABLE OT.SENSOR_READINGS (
  ASSET_ID        VARCHAR      NOT NULL,
  READING_TS      TIMESTAMP_NTZ NOT NULL,
  VIBRATION_MM_S  FLOAT  COMMENT 'Overall vibration velocity RMS (mm/s)',
  TEMPERATURE_C   FLOAT  COMMENT 'Bearing / housing temperature (deg C)',
  RPM             FLOAT  COMMENT 'Shaft speed',
  CURRENT_A       FLOAT  COMMENT 'Motor phase current (A)'
) CLUSTER BY (ASSET_ID, TO_DATE(READING_TS))
  COMMENT = '10-minute condition-monitoring telemetry from PLC/historian';

-- ---------- ERP / CMMS ----------
CREATE OR REPLACE TABLE ERP.PRODUCTION_LINES (
  LINE_ID VARCHAR PRIMARY KEY, PLANT_CODE VARCHAR, PLANT_NAME VARCHAR, LINE_NAME VARCHAR, OEE_TARGET FLOAT
);
INSERT INTO ERP.PRODUCTION_LINES VALUES
  ('PUN-L1','PUN','Pune Assembly Plant','Pune Line 1 - Engine block machining',0.80),
  ('PUN-L2','PUN','Pune Assembly Plant','Pune Line 2 - Cylinder head machining',0.80),
  ('CHN-L1','CHN','Chennai Machining Plant','Chennai Line 1 - Crankshaft line',0.80),
  ('CHN-L2','CHN','Chennai Machining Plant','Chennai Line 2 - Gear housing line',0.80);

CREATE OR REPLACE TABLE ERP.ASSETS (
  ASSET_ID VARCHAR PRIMARY KEY, ASSET_NAME VARCHAR, ASSET_TYPE VARCHAR, TYPE_CODE VARCHAR,
  PLANT_CODE VARCHAR, PLANT_NAME VARCHAR, LINE_ID VARCHAR, MANUFACTURER VARCHAR, INSTALL_DATE DATE,
  CRITICALITY VARCHAR COMMENT 'A = line stops, B = degraded output, C = minor',
  RATED_RPM FLOAT, BASE_VIBRATION_MM_S FLOAT, VIBRATION_ALARM_MM_S FLOAT, TEMP_ALARM_C FLOAT,
  RATED_CURRENT_A FLOAT, PM_INTERVAL_DAYS NUMBER, COST_CENTER VARCHAR
) COMMENT = 'Asset master (ERP PM module)';

CREATE OR REPLACE TABLE ERP.FAILURE_EVENTS (
  FAILURE_ID VARCHAR PRIMARY KEY, ASSET_ID VARCHAR, FAILURE_TS TIMESTAMP_NTZ, FAILURE_MODE VARCHAR,
  FAILURE_DESCRIPTION VARCHAR, DOWNTIME_HOURS FLOAT, DETECTED_BY VARCHAR
) COMMENT = 'Historical functional failures (labels for ML)';

CREATE OR REPLACE TABLE ERP.WORK_ORDERS (
  WO_ID VARCHAR PRIMARY KEY, ASSET_ID VARCHAR, WO_TYPE VARCHAR COMMENT 'PM preventive, CM corrective, PDM predictive',
  PRIORITY VARCHAR, STATUS VARCHAR, CREATED_TS TIMESTAMP_NTZ, SCHEDULED_TS TIMESTAMP_NTZ, CLOSED_TS TIMESTAMP_NTZ,
  FAILURE_MODE VARCHAR, DESCRIPTION VARCHAR, TECHNICIAN_NOTES VARCHAR, PARTS_USED VARCHAR,
  LABOR_HOURS FLOAT, COST_INR NUMBER, DOWNTIME_HOURS FLOAT, SOURCE VARCHAR,
  -- populated for predictive work orders created by PlantPulse
  ALERT_ID VARCHAR, RISK_SCORE FLOAT, AI_JOB_PLAN VARCHAR, CREATED_BY VARCHAR
) COMMENT = 'CMMS work orders incl. free-text technician notes';

CREATE OR REPLACE TABLE ERP.SPARE_PARTS (
  PART_NO VARCHAR PRIMARY KEY, DESCRIPTION VARCHAR, COMPATIBLE_ASSET_TYPES VARCHAR,
  ON_HAND_QTY NUMBER, LEAD_TIME_DAYS NUMBER, UNIT_COST_INR NUMBER
) COMMENT = 'MRO spare parts inventory';

CREATE OR REPLACE TABLE ERP.PRODUCTION_LOG (
  LINE_ID VARCHAR, PLANT_CODE VARCHAR, PROD_DATE DATE, SHIFT VARCHAR, SHIFT_START_TS TIMESTAMP_NTZ,
  PLANNED_TIME_MIN FLOAT, BREAKDOWN_MIN FLOAT, MINOR_STOP_MIN FLOAT, CHANGEOVER_MIN FLOAT, RUN_TIME_MIN FLOAT,
  IDEAL_CYCLE_TIME_S FLOAT, TOTAL_COUNT NUMBER, GOOD_COUNT NUMBER
) COMMENT = 'Shift production counts from MES';

-- ---------- Knowledge ----------
CREATE OR REPLACE TABLE KNOWLEDGE.MAINTENANCE_DOCS (
  DOC_ID VARCHAR PRIMARY KEY, DOC_TITLE VARCHAR, ASSET_TYPE VARCHAR, FAILURE_MODE VARCHAR, CONTENT VARCHAR
) COMMENT = 'OEM manual excerpts, SOPs and reliability reviews (chunked)';

-- ---------- Landing stage ----------
CREATE OR REPLACE FILE FORMAT ERP.CSV_FF
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'nan', 'NaN', 'None') EMPTY_FIELD_AS_NULL = TRUE
  TIMESTAMP_FORMAT = 'AUTO' DATE_FORMAT = 'AUTO';
CREATE OR REPLACE STAGE ERP.LANDING FILE_FORMAT = ERP.CSV_FF COMMENT = 'CSV landing zone';
