-- =====================================================================
-- PlantPulse | 01 - Load CSVs from the landing stage
-- Files are uploaded by scripts/load_data.py (PUT) or Snowsight upload:
--   @PLANTPULSE.ERP.LANDING/<name>.csv.gz
-- =====================================================================
USE WAREHOUSE PLANTPULSE_WH;
USE DATABASE PLANTPULSE;

TRUNCATE TABLE IF EXISTS ERP.ASSETS;
COPY INTO ERP.ASSETS (ASSET_ID, ASSET_NAME, ASSET_TYPE, TYPE_CODE, PLANT_CODE, PLANT_NAME, LINE_ID, MANUFACTURER,
  INSTALL_DATE, CRITICALITY, RATED_RPM, BASE_VIBRATION_MM_S, VIBRATION_ALARM_MM_S, TEMP_ALARM_C, RATED_CURRENT_A,
  PM_INTERVAL_DAYS, COST_CENTER)
FROM @ERP.LANDING FILES = ('assets.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS OT.SENSOR_READINGS;
COPY INTO OT.SENSOR_READINGS (ASSET_ID, READING_TS, VIBRATION_MM_S, TEMPERATURE_C, RPM, CURRENT_A)
FROM @ERP.LANDING FILES = ('sensor_readings.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ERP.FAILURE_EVENTS;
COPY INTO ERP.FAILURE_EVENTS (FAILURE_ID, ASSET_ID, FAILURE_TS, FAILURE_MODE, FAILURE_DESCRIPTION, DOWNTIME_HOURS, DETECTED_BY)
FROM @ERP.LANDING FILES = ('failure_events.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ERP.WORK_ORDERS;
COPY INTO ERP.WORK_ORDERS (WO_ID, ASSET_ID, WO_TYPE, PRIORITY, STATUS, CREATED_TS, SCHEDULED_TS, CLOSED_TS, FAILURE_MODE,
  DESCRIPTION, TECHNICIAN_NOTES, PARTS_USED, LABOR_HOURS, COST_INR, DOWNTIME_HOURS, SOURCE)
FROM @ERP.LANDING FILES = ('work_orders.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ERP.SPARE_PARTS;
COPY INTO ERP.SPARE_PARTS (PART_NO, DESCRIPTION, COMPATIBLE_ASSET_TYPES, ON_HAND_QTY, LEAD_TIME_DAYS, UNIT_COST_INR)
FROM @ERP.LANDING FILES = ('spare_parts.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ERP.PRODUCTION_LOG;
COPY INTO ERP.PRODUCTION_LOG (LINE_ID, PLANT_CODE, PROD_DATE, SHIFT, SHIFT_START_TS, PLANNED_TIME_MIN, BREAKDOWN_MIN,
  MINOR_STOP_MIN, CHANGEOVER_MIN, RUN_TIME_MIN, IDEAL_CYCLE_TIME_S, TOTAL_COUNT, GOOD_COUNT)
FROM @ERP.LANDING FILES = ('production_log.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS KNOWLEDGE.MAINTENANCE_DOCS;
COPY INTO KNOWLEDGE.MAINTENANCE_DOCS (DOC_ID, DOC_TITLE, ASSET_TYPE, FAILURE_MODE, CONTENT)
FROM @ERP.LANDING FILES = ('maintenance_docs.csv.gz') FILE_FORMAT = (FORMAT_NAME = ERP.CSV_FF) ON_ERROR = ABORT_STATEMENT;

-- Sanity check
SELECT 'ASSETS' T, COUNT(*) N FROM ERP.ASSETS UNION ALL
SELECT 'SENSOR_READINGS', COUNT(*) FROM OT.SENSOR_READINGS UNION ALL
SELECT 'FAILURE_EVENTS', COUNT(*) FROM ERP.FAILURE_EVENTS UNION ALL
SELECT 'WORK_ORDERS', COUNT(*) FROM ERP.WORK_ORDERS UNION ALL
SELECT 'SPARE_PARTS', COUNT(*) FROM ERP.SPARE_PARTS UNION ALL
SELECT 'PRODUCTION_LOG', COUNT(*) FROM ERP.PRODUCTION_LOG UNION ALL
SELECT 'MAINTENANCE_DOCS', COUNT(*) FROM KNOWLEDGE.MAINTENANCE_DOCS;
