-- =====================================================================
-- PlantPulse | 03 - Failure prediction (Snowflake ML Classification)
--   Label: does the asset suffer a functional failure in the next 72 hours?
--   Final risk = 60% ML probability + 40% explainable rule score
-- =====================================================================
USE WAREHOUSE PLANTPULSE_WH;
USE DATABASE PLANTPULSE;
USE SCHEMA ANALYTICS;

-- Training set: features + label. Hours in the last 72h are excluded (label not yet known);
-- hours right after a breakdown are excluded (rolling windows still contain pre-failure data).
CREATE OR REPLACE VIEW ANALYTICS.V_TRAINING_SET AS
WITH lbl AS (
  SELECT f.ASSET_ID, f.HOUR_TS,
         COUNT_IF(fe.FAILURE_TS >  f.HOUR_TS AND fe.FAILURE_TS <= DATEADD('hour', 72, f.HOUR_TS)) AS N_FUTURE,
         COUNT_IF(fe.FAILURE_TS <= f.HOUR_TS AND fe.FAILURE_TS >  DATEADD('hour', -(30 + fe.DOWNTIME_HOURS), f.HOUR_TS)) AS N_RECENT
  FROM ANALYTICS.ASSET_FEATURES f
  LEFT JOIN ERP.FAILURE_EVENTS fe ON fe.ASSET_ID = f.ASSET_ID
  GROUP BY 1, 2
)
SELECT f.ASSET_TYPE, f.CRITICALITY,
       f.VIB_RATIO, f.VIB_ALARM_RATIO, f.VIB_CV, f.TEMP_DELTA, f.TEMP_MARGIN, f.CUR_RATIO, f.CUR_VOLATILITY,
       f.RPM_CV, f.VIB_SLOPE_PER_DAY, f.TEMP_SLOPE_PER_DAY, f.PM_OVERDUE_DAYS,
       IFF(l.N_FUTURE > 0, 'FAIL', 'OK') AS FAILURE_72H
FROM ANALYTICS.ASSET_FEATURES f
JOIN lbl l ON l.ASSET_ID = f.ASSET_ID AND l.HOUR_TS = f.HOUR_TS
WHERE l.N_RECENT = 0
  AND f.HOUR_TS <= (SELECT DATEADD('hour', -72, MAX(HOUR_TS)) FROM ANALYTICS.ASSET_FEATURES);

-- Train (takes ~2-4 minutes on an XS warehouse)
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ANALYTICS.FAILURE_RISK_MODEL(
  INPUT_DATA     => SYSTEM$REFERENCE('VIEW', 'PLANTPULSE.ANALYTICS.V_TRAINING_SET'),
  TARGET_COLNAME => 'FAILURE_72H',
  CONFIG_OBJECT  => {'evaluate': TRUE, 'on_error': 'skip'}
);

-- Model quality & explainability
CALL ANALYTICS.FAILURE_RISK_MODEL!SHOW_GLOBAL_EVALUATION_METRICS();
CALL ANALYTICS.FAILURE_RISK_MODEL!SHOW_EVALUATION_METRICS();
CALL ANALYTICS.FAILURE_RISK_MODEL!SHOW_FEATURE_IMPORTANCE();

-- ---------------------------------------------------------------------
-- Scoring procedure: refresh features, score latest hour per asset,
-- write ANALYTICS.ASSET_RISK_SCORES (+ append history).
-- Falls back to the rule score if the ML model is unavailable.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ANALYTICS.ASSET_RISK_HISTORY (
  SCORED_AT TIMESTAMP_NTZ, ASSET_ID VARCHAR, HOUR_TS TIMESTAMP_NTZ, ML_PROB FLOAT, RULE_SCORE FLOAT,
  RISK_SCORE FLOAT, RISK_BAND VARCHAR, SUSPECTED_MODE VARCHAR, HOURS_TO_ALARM FLOAT
);

CREATE OR REPLACE PROCEDURE ANALYTICS.SCORE_ASSETS(USE_ML BOOLEAN DEFAULT TRUE)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Refresh features and compute failure risk for every asset'
AS
$$
DECLARE
  n INTEGER;
  ml_status VARCHAR DEFAULT 'rules-only';
BEGIN
  CREATE OR REPLACE TABLE PLANTPULSE.ANALYTICS.ASSET_FEATURES AS SELECT * FROM PLANTPULSE.ANALYTICS.V_ASSET_FEATURES;

  CREATE OR REPLACE TEMPORARY TABLE PLANTPULSE.ANALYTICS.TMP_LATEST AS
    SELECT * FROM PLANTPULSE.ANALYTICS.V_RULE_HEALTH
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY HOUR_TS DESC) = 1;

  CREATE OR REPLACE TEMPORARY TABLE PLANTPULSE.ANALYTICS.TMP_ML AS
    SELECT ASSET_ID, NULL::FLOAT AS ML_PROB FROM PLANTPULSE.ANALYTICS.TMP_LATEST;

  IF (USE_ML) THEN
    BEGIN
      CREATE OR REPLACE TEMPORARY TABLE PLANTPULSE.ANALYTICS.TMP_ML AS
        SELECT ASSET_ID,
               PLANTPULSE.ANALYTICS.FAILURE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT_KEEP_NULL(
                 'ASSET_TYPE', ASSET_TYPE, 'CRITICALITY', CRITICALITY, 'VIB_RATIO', VIB_RATIO,
                 'VIB_ALARM_RATIO', VIB_ALARM_RATIO, 'VIB_CV', VIB_CV, 'TEMP_DELTA', TEMP_DELTA,
                 'TEMP_MARGIN', TEMP_MARGIN, 'CUR_RATIO', CUR_RATIO, 'CUR_VOLATILITY', CUR_VOLATILITY,
                 'RPM_CV', RPM_CV, 'VIB_SLOPE_PER_DAY', VIB_SLOPE_PER_DAY, 'TEMP_SLOPE_PER_DAY', TEMP_SLOPE_PER_DAY,
                 'PM_OVERDUE_DAYS', PM_OVERDUE_DAYS)):probability:FAIL::FLOAT AS ML_PROB
        FROM PLANTPULSE.ANALYTICS.TMP_LATEST;
      ml_status := 'ml+rules';
    EXCEPTION
      WHEN OTHER THEN ml_status := 'rules-only (model unavailable: ' || SQLERRM || ')';
    END;
  END IF;

  CREATE OR REPLACE TABLE PLANTPULSE.ANALYTICS.ASSET_RISK_SCORES AS
  SELECT l.ASSET_ID, a.ASSET_NAME, a.ASSET_TYPE, a.LINE_ID, a.PLANT_NAME, a.CRITICALITY, l.HOUR_TS AS AS_OF_TS,
         ROUND(m.ML_PROB, 4) AS ML_PROB, l.RULE_SCORE,
         ROUND(IFF(m.ML_PROB IS NULL, l.RULE_SCORE, 0.6 * m.ML_PROB * 100 + 0.4 * l.RULE_SCORE), 1) AS RISK_SCORE,
         CASE WHEN ROUND(IFF(m.ML_PROB IS NULL, l.RULE_SCORE, 0.6 * m.ML_PROB * 100 + 0.4 * l.RULE_SCORE), 1) >= 50 THEN 'HIGH'
              WHEN ROUND(IFF(m.ML_PROB IS NULL, l.RULE_SCORE, 0.6 * m.ML_PROB * 100 + 0.4 * l.RULE_SCORE), 1) >= 30 THEN 'MEDIUM'
              ELSE 'LOW' END AS RISK_BAND,
         l.SUSPECTED_MODE, ROUND(l.HOURS_TO_ALARM, 1) AS HOURS_TO_ALARM,
         ROUND(l.VIB_AVG_24H, 2) AS VIB_AVG_24H, ROUND(l.BASE_VIB, 2) AS BASE_VIB, ROUND(l.VIB_RATIO, 2) AS VIB_RATIO,
         ROUND(l.TEMP_AVG_24H, 1) AS TEMP_AVG_24H, ROUND(l.TEMP_DELTA, 1) AS TEMP_DELTA,
         ROUND(l.CUR_RATIO, 3) AS CUR_RATIO, ROUND(l.VIB_SLOPE_PER_DAY, 3) AS VIB_SLOPE_PER_DAY,
         ROUND(l.TEMP_SLOPE_PER_DAY, 2) AS TEMP_SLOPE_PER_DAY, l.SATURATED_24H, l.DAYS_SINCE_PM, l.PM_OVERDUE_DAYS,
         l.VIBRATION_ALARM_MM_S, l.TEMP_ALARM_C,
         CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS SCORED_AT
  FROM PLANTPULSE.ANALYTICS.TMP_LATEST l
  JOIN PLANTPULSE.ERP.ASSETS a ON a.ASSET_ID = l.ASSET_ID
  LEFT JOIN PLANTPULSE.ANALYTICS.TMP_ML m ON m.ASSET_ID = l.ASSET_ID;

  INSERT INTO PLANTPULSE.ANALYTICS.ASSET_RISK_HISTORY
    SELECT SCORED_AT, ASSET_ID, AS_OF_TS, ML_PROB, RULE_SCORE, RISK_SCORE, RISK_BAND, SUSPECTED_MODE, HOURS_TO_ALARM
    FROM PLANTPULSE.ANALYTICS.ASSET_RISK_SCORES;

  SELECT COUNT_IF(RISK_BAND = 'HIGH') INTO :n FROM PLANTPULSE.ANALYTICS.ASSET_RISK_SCORES;
  RETURN 'Scored all assets (' || ml_status || '). High-risk assets: ' || n;
END;
$$;

CALL ANALYTICS.SCORE_ASSETS(TRUE);
SELECT ASSET_ID, RISK_SCORE, RISK_BAND, ML_PROB, RULE_SCORE, SUSPECTED_MODE, HOURS_TO_ALARM
FROM ANALYTICS.ASSET_RISK_SCORES ORDER BY RISK_SCORE DESC LIMIT 10;

-- Back-test: how early would PlantPulse have warned before each historical failure?
CREATE OR REPLACE VIEW ANALYTICS.V_BACKTEST AS
SELECT fe.FAILURE_ID, fe.ASSET_ID, fe.FAILURE_MODE, fe.FAILURE_TS, fe.DOWNTIME_HOURS,
       MIN(IFF(r.RULE_SCORE >= 30, r.HOUR_TS, NULL)) AS FIRST_WARNING_TS,
       DATEDIFF('hour', MIN(IFF(r.RULE_SCORE >= 30, r.HOUR_TS, NULL)), fe.FAILURE_TS) AS LEAD_TIME_HOURS,
       MAX_BY(r.SUSPECTED_MODE, r.HOUR_TS) AS PREDICTED_MODE,
       (MAX_BY(r.SUSPECTED_MODE, r.HOUR_TS) = fe.FAILURE_MODE) AS MODE_CORRECT
FROM ERP.FAILURE_EVENTS fe
JOIN ANALYTICS.V_RULE_HEALTH r
  ON r.ASSET_ID = fe.ASSET_ID AND r.HOUR_TS < fe.FAILURE_TS AND r.HOUR_TS >= DATEADD('day', -8, fe.FAILURE_TS)
GROUP BY 1, 2, 3, 4, 5;

SELECT * FROM ANALYTICS.V_BACKTEST ORDER BY FAILURE_TS;
